/*-------------------------------------------------------------------------
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED 2024-04-24 20:09:47
 *
 *-------------------------------------------------------------------------
 */

#pragma once

#include <avr/io.h>
#include <avr/pgmspace.h>
#include <stdint.h>

#include "sprite.h"

/* sp_band_select_pointer */
static const uint8_t sp_band_select_pointer_data[] PROGMEM = {
	0xF8,
	0x70,
	0x20,
};

static const Sprite sp_band_select_pointer = {
	.width	= 3,
	.height	= 5,
	.data	= sp_band_select_pointer_data,
};

