/*-------------------------------------------------------------------------
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED 2024-04-24 20:09:46
 *
 *-------------------------------------------------------------------------
 */

#pragma once

#include <avr/io.h>
#include <avr/pgmspace.h>
#include <stdint.h>

#include "sprite.h"

/* sp_mono */
static const uint8_t sp_mono_data[] PROGMEM = {
	0xFE,
	0x40,
	0x30,
	0x40,
	0xFE,
	0x00,
	0x7C,
	0x82,
	0x82,
	0x82,
	0x7C,
	0x00,
	0xFE,
	0x20,
	0x10,
	0x08,
	0xFE,
	0x00,
	0x7C,
	0x82,
	0x82,
	0x82,
	0x7C,
};

static const Sprite sp_mono = {
	.width	= 23,
	.height	= 7,
	.data	= sp_mono_data,
};

