/*-------------------------------------------------------------------------
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED 2024-04-24 20:09:46
 *
 *-------------------------------------------------------------------------
 */

#pragma once

#include <avr/io.h>
#include <avr/pgmspace.h>
#include <stdint.h>

#include "sprite.h"

/* sp_stereo */
static const uint8_t sp_stereo_data[] PROGMEM = {
	0x64,
	0x92,
	0x92,
	0x92,
	0x4C,
	0x00,
	0x80,
	0x80,
	0xFE,
	0x80,
	0x80,
	0x00,
	0xFE,
	0x92,
	0x92,
	0x92,
	0x82,
	0x00,
	0xFE,
	0x90,
	0x98,
	0x94,
	0x62,
	0x00,
	0xFE,
	0x92,
	0x92,
	0x92,
	0x82,
	0x00,
	0x7C,
	0x82,
	0x82,
	0x82,
	0x7C,
};

static const Sprite sp_stereo = {
	.width	= 35,
	.height	= 7,
	.data	= sp_stereo_data,
};

